# This is a basic workflow to help you get started with Actions

name: ci-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    name: Test
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it


      # Runs a single command using the runners shell
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.8
        id: go

      # Runs a set of commands using the runners shell
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2


      - name: Test
        run: go test -v -cover ./...
